const $ = require('jquery')
const allFoods = require('../ajax-requests/getAllFoods')
const calories = require('../objects/diaryCalorieCounts')
const filterFoods = require('../objects/foodsTableFilter')
const addToMeal = require('../objects/addItemsToMeal')
const getMeals = require('../ajax-requests/getMeals')

$(document).ready(function() {
  $('body.diary').on('load', getMeals.loadMeals())
  $('body.diary').on('load', allFoods.getFoodsDiary())
  $('#diary-food-input').keyup(filterFoods.filterDiaryFoods)
  $('button.breakfast').on('click', addToMeal.addToMeal)
  $('button.lunch').on('click', addToMeal.addToMeal)
  $('button.dinner').on('click', addToMeal.addToMeal)
  $('button.snack').on('click', addToMeal.addToMeal)
})
