require('./styles/foods.css')
require('./styles/diary.css')
// require('./ajax-requests/getAllFoods')
// require('./ajax-requests/deleteFood')
// require('./ajax-requests/postFood')
require('./ajax-responses/foodResponses')
require('./event-listeners/foodsListeners')
require('./event-listeners/diaryListeners')
// require('./objects/foodsTableFilter')
// require('./objects/totalsTable')
// require('./objects/diaryCalorieCounts')
// require('./ajax-requests/editFoods')
// require('./ajax-requests/getSingleFood')
// require('./ajax-requests/getMeals')
// require('./ajax-requests/postMealItems')
// require('./objects/addItemsToMeal')
// require('./objects/filterCalories')

require('./ajax-requests/requestsIndex')
require('./objects/requestsIndex')
